services:
    uptime:
        image: louislam/uptime-kuma
        restart: always
        volumes:
            - uptime_data:/app/data
        networks:
            - traefik-net

volumes:
    uptime_data:

networks:
    traefik-net:
        external: true
