services:
    adguard:
        image: adguard/adguardhome
        container_name: adh
        restart: always
        environment:
            - TZ=Asia/Shanghai
        network_mode: host
        extra_hosts:
            - "host.docker.internal:192.168.31.109"
        volumes:
            - adguard_work:/opt/adguardhome/work
            - adguard_conf:/opt/adguardhome/conf

volumes:
    adguard_work:
    adguard_conf:
